index:
    path: /
    controller: App\Controller\PageController::index
admin:
    path: /admin
    controller: App\Controller\PageController::admin

contact:
    path: /contact
    controller: App\Controller\ContactController::contact

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_registration:
    path: /register
    controller: App\Controller\RegistrationController::register

app_logout:
    path: /logout