index:
    path: /
    controller: App\Controller\PageController::index

contact:
    path: /contact
    controller: App\Controller\ContactController::contact

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_registration:
    path: /register
    controller: App\Controller\RegistrationController::register

app_activation:
    path: /activate/{token}/{user}
    controller: App\Controller\AccountController::activate
    requirements:
        user: \d+

app_logout:
    path: /logout

user_account:
    path: /account
    controller: App\Controller\AccountController::account

user_edit:
    path: /account/edit/{user}
    controller: App\Controller\AccountController::editAction
    requirements:
        user: \d+

user_delete:
    path: /account/delete/{user}
    controller: App\Controller\AccountController::deleteAction
    requirements:
        user: \d+

admin_list:
    path: /admin
    controller: App\Controller\AdminController::showList

admin_add:
    path: /admin/add
    controller: App\Controller\AdminController::addAction

admin_edit:
    path: /admin/edit/{id}
    controller: App\Controller\AdminController::editAction

admin_delete:
    path: /admin/delete/{id}
    controller: App\Controller\AdminController::deleteAction